# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8de408a1bda79da2b8a0eabe57b092c9114d5818b1287f2bb01bd9b8b4b85cd0519ae42d7745af4a6dcfd494cd32cd3c6e26af2db17685ab20011388e7ce9a91

test:
  secret_key_base: f50aaf5d2907dc229868dec7b760a687e407054dddf8c7fd9174876b312998ce63f56c3034e943d85743a139789beac03022bf5daa284e60637e919e6471ac72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
